// The node union, the custom-node schema, and the Y.Doc contract constants live in
// @tradstry/notebook-core, shared verbatim with the desktop and the web clients.
// One wire format, one place.
//
// `notebook-core.gen.mjs` is generated by `bun run sync-core`. It is built INTO
// this directory so its bare `@lexical/*` imports resolve from the projector's
// node_modules — a second Lexical copy would break class identity.
export {
  NODES,
  stripGhostText,
  DOC_ID,
  NAMESPACE,
} from "./notebook-core.gen.mjs";
