import type { EditorThemeClasses } from "lexical";

export const notebookEditorTheme: EditorThemeClasses = {
  ltr: "text-left",
  rtl: "text-right",
  paragraph: "mb-3 leading-7 text-[15px] text-foreground/80",
  quote:
    "my-4 rounded-r-2xl border-l-4 border-l-amber-400 bg-amber-50/70 dark:bg-amber-950/30 px-4 py-3 text-foreground/80",
  heading: {
    h1: "nb-title relative mt-6 mb-3 text-3xl font-semibold leading-tight tracking-tight text-foreground first:mt-0",
    h2: "mt-5 mb-3 text-2xl font-semibold tracking-tight text-foreground",
    h3: "mt-4 mb-2 text-xl font-semibold tracking-tight text-foreground",
    h4: "mt-4 mb-2 text-lg font-semibold text-foreground",
    h5: "mt-3 mb-2 text-base font-semibold text-foreground",
    h6: "mt-3 mb-2 text-sm font-semibold uppercase tracking-[0.16em] text-foreground/80",
  },
  list: {
    ol: "my-3 list-decimal pl-6 text-[15px] text-foreground/80",
    ul: "my-3 list-disc pl-6 text-[15px] text-foreground/80",
    listitem: "my-1 pl-1",
    nested: {
      list: "mt-1",
    },
  },
  text: {
    bold: "font-semibold text-foreground",
    code: "rounded bg-muted px-1.5 py-0.5 font-mono text-[0.9em] text-foreground",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline underline-offset-4",
  },
  link: "font-medium text-sky-700 dark:text-sky-400 underline decoration-sky-300 dark:decoration-sky-600 underline-offset-4",
  code: "block overflow-x-auto rounded-2xl bg-slate-950 px-4 py-3 font-mono text-sm leading-6 text-slate-100",
  codeHighlight: {
    atrule: "text-fuchsia-300",
    attr: "text-cyan-300",
    boolean: "text-amber-300",
    builtin: "text-emerald-300",
    cdata: "text-slate-400",
    char: "text-emerald-300",
    class: "text-cyan-200",
    "class-name": "text-cyan-200",
    comment: "text-slate-500",
    constant: "text-amber-200",
    deleted: "text-rose-300",
    doctype: "text-slate-500",
    entity: "text-fuchsia-300",
    function: "text-blue-300",
    important: "text-amber-200",
    inserted: "text-emerald-300",
    keyword: "text-fuchsia-300",
    namespace: "text-slate-300",
    number: "text-amber-300",
    operator: "text-slate-200",
    prolog: "text-slate-500",
    property: "text-cyan-300",
    punctuation: "text-slate-300",
    regex: "text-rose-300",
    selector: "text-cyan-300",
    string: "text-emerald-300",
    symbol: "text-amber-200",
    tag: "text-blue-300",
    url: "text-sky-300",
    variable: "text-orange-300",
  },
};
